import { Trail } from '@/types';

export const initialTrails: Trail[] = [
  {
    id: 'serpents-pass',
    name: "Serpent's Pass",
    description: 'A winding, challenging trail known for its steep inclines and breathtaking summit views. Popular among experienced hikers.',
    location: 'Dragon\'s Tooth Mountains',
    distance: 12.5,
    duration: 6,
    difficulty: 'Hard',
    terrain: ['Mountain'],
    hasHistoricalElements: true,
    imageUrl: 'https://placehold.co/400x250/2E4F2E/C2B280',
    imageHint: 'mountain pass',
    averageRating: 4.8,
  },
  {
    id: 'whispering-woods-loop',
    name: 'Whispering Woods Loop',
    description: 'A serene, family-friendly loop through an ancient forest, famous for its towering trees and diverse wildlife.',
    location: 'Elderwood Forest',
    distance: 5.2,
    duration: 2.5,
    difficulty: 'Easy',
    terrain: ['Forest'],
    hasHistoricalElements: false,
    imageUrl: 'https://placehold.co/400x250/5C4033/C2B280',
    imageHint: 'forest path',
    averageRating: 4.5,
  },
  {
    id: 'coastal-sentinel-trail',
    name: 'Coastal Sentinel Trail',
    description: 'Follow the dramatic cliffs of the coastline, offering stunning ocean vistas and access to secluded beaches. Watch for seabirds!',
    location: 'Azure Coast',
    distance: 8.0,
    duration: 3.5,
    difficulty: 'Moderate',
    terrain: ['Coastal'],
    hasHistoricalElements: true,
    imageUrl: 'https://placehold.co/400x250/C2B280/2E4F2E',
    imageHint: 'coastal cliff',
    averageRating: 4.7,
  },
  {
    id: 'giants-staircase',
    name: "Giant's Staircase",
    description: 'A strenuous climb up a series of natural rock steps, rewarding hikers with unparalleled panoramic views of the entire region.',
    location: 'Dragon\'s Tooth Mountains',
    distance: 9.8,
    duration: 7,
    difficulty: 'Expert',
    terrain: ['Mountain'],
    hasHistoricalElements: false,
    imageUrl: 'https://placehold.co/400x250/2E4F2E/FFFFFF',
    imageHint: 'rocky staircase',
    averageRating: 4.9,
  },
  {
    id: 'riverbend-meadow-walk',
    name: 'Riverbend Meadow Walk',
    description: 'A flat and pleasant walk alongside a meandering river, perfect for picnics, bird watching, and a relaxing day out.',
    location: 'Green Valley',
    distance: 3.1,
    duration: 1.5,
    difficulty: 'Easy',
    terrain: ['Forest', 'Coastal'],
    hasHistoricalElements: false,
    imageUrl: 'https://placehold.co/400x250/556B2F/FFFFF0',
    imageHint: 'river meadow',
    averageRating: 4.3,
  },
  {
    id: 'sunstone-canyon-trek',
    name: 'Sunstone Canyon Trek',
    description: 'Explore the arid beauty of Sunstone Canyon, with its unique rock formations and resilient desert flora. Best hiked in cooler months.',
    location: 'The Arid Expanse',
    distance: 15.0,
    duration: 8,
    difficulty: 'Hard',
    terrain: ['Desert'],
    hasHistoricalElements: true,
    imageUrl: 'https://placehold.co/400x250/D2B48C/5C4033',
    imageHint: 'desert canyon',
    averageRating: 4.6,
  },
  {
    id: 'forgotten-fortress-path',
    name: 'Forgotten Fortress Path',
    description: 'A trail leading to the ruins of an ancient fortress, blending natural beauty with a sense of history and mystery.',
    location: 'Elderwood Forest',
    distance: 6.5,
    duration: 3,
    difficulty: 'Moderate',
    terrain: ['Forest', 'Mountain'],
    hasHistoricalElements: true,
    imageUrl: 'https://placehold.co/400x250/8FBC8F/2F4F4F',
    imageHint: 'castle ruins',
    averageRating: 4.8,
  },
  {
    id: 'crystal-creek-trail',
    name: 'Crystal Creek Trail',
    description: 'This trail follows a crystal-clear creek up to a series of small, beautiful waterfalls. Ideal for a hot day.',
    location: 'Green Valley',
    distance: 4.0,
    duration: 2,
    difficulty: 'Easy',
    terrain: ['Forest'],
    hasHistoricalElements: false,
    imageUrl: 'https://placehold.co/400x250/B0E0E6/4682B4',
    imageHint: 'creek waterfall',
    averageRating: 4.7,
  },
];
